lista_palavras_forca=[
    'desenvolvedor',
    'abacate',
    'bootcamp',
    'computador',
    'instituto',
    'python',
    'cadeira',
    'felicidade',
    'pessoas',
    'alegria',
    'amor'
    ]
